---
- hosts: localhost
  tasks:
    - name: Install rtk node.js package
      community.general.npm:
        name: rtk
        version: '{{ rtk_version }}'
        global: true
    - name: Install git package
      ansible.builtin.package:
        name: git
        state: present
